server:
  servlet:
    context-path: /${spring.application.name}
  port: 8080
  tomcat:
    threads:
      max: 400
      min-spare: 100
    accept-count: 1000

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
  config: classpath:logback-spring.xml

spring:
  application:
    name: my-app
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: 512MB
      max-file-size: 512MB
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: Asia/Shanghai
  mvc:
    format:
      date: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
      date-time: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 1000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      batch-size: 16384
      acks: -1
      retries: 10
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
          ms: 2000
    consumer:
      group-id: my-app
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session:
          timeout:
            ms: 30000
        request:
          timeout:
            ms : 30000
    listener:
      missing-topics-fatal: false
      type: batch
      ack-mode: manual